### ISSUE TITLE
Docusarus 3.6.0 upgrade breaks this package

### ISSUE THREAD

**Issue by Celtech** [PaloAltoNetworks/docusaurus-openapi-docs#1013]
## Describe the bug

If you upgrade a docusarus site to the 3.6.0 release it will trigger the following error when you do a `yarn start`

```
Hook useScrollController is called outside the <ScrollControllerProvider>. 
ReactContextError
    at useScrollController (webpack-internal:///./node_modules/docusaurus-theme-openapi-docs/node_modules/@docusaurus/theme-common/lib/utils/scrollUtils.js:27:145)
    at useScrollPositionBlocker (webpack-internal:///./node_modules/docusaurus-theme-openapi-docs/node_modules/@docusaurus/theme-common/lib/utils/scrollUtils.js:45:63)
    at TabList (webpack-internal:///./node_modules/docusaurus-theme-openapi-docs/lib/theme/MimeTabs/index.js:6:2109)
    at renderWithHooks (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:15487:18)
    at mountIndeterminateComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20099:13)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21622:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4165:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4214:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4278:31)
    at beginWork$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:27486:7)
```

## Steps to reproduce

1.
2.
3.
4.

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by pmarschik** [comment]
I've done the upgrade to docusaurus 3.6.0 but I've also upgraded docusaurus-openapi-docs to 4.2.0 in the same change.
With 4.2.0 I don't get the error you describe.

In the [mentioned PR](https://github.com/eclipse-apoapsis/ort-server/pull/1359) docusaurus-openapi-docs is still on 4.1.0 so maybe upgrading to 4.2.0 helps?

**Comment by pmarschik** [comment]
Yes. Interesting, must be some other issue then since I couldn't reproduce your issue and I'm using docusaurus 3.6.0 + @docusaurus/faster + docusuarus-openapi-docs 4.2.0.

**Comment by alvinometric** [comment]
Also getting the same issue with `Hook useScrollController is called outside the <ScrollControllerProvider>` when upgrading to Docusaurus 3.6 and version 4.2 of this plugin

**Comment by alvinometric** [comment]
@sserrata Unfortunately this seems to persist even with:
- a fresh lockfile
- deleting the generated mdx files
- upgrading to the canary release of this plugin (both the theme and the plugin)

**Comment by sserrata** [comment]
Ah, I just realized you may still be on 4.2.0, which doesn't support Docusaurus 3.6.0. If that's the case, can you upgrade to the latest canary release?

**Comment by sserrata** [comment]
Just read your latest comment...not sure what the issue could be since the demo site is currently on Docusaurus 3.6.0 and I've not been able to repro locally.

**Comment by ianbaek** [comment]
I had the same issue of 'Hook useScrollController is called outside the <ScrollControllerProvider>' after updating to 4.2.0 at Docusarus 3.5.2. Upgrading Docusarus to 3.6 in my case solved the issue. It might be some dependency issue but could not find exactly what caused the issue.

**Comment by otuoche** [comment]
i am still having the same issue too

**Comment by ChrisSargent** [comment]
`yarn dedupe` solved it for us

**Comment by sschuberth** [comment]
> `yarn dedupe` solved it for us

Didn't help in [our case](https://github.com/eclipse-apoapsis/ort-server/actions/runs/11816223090/job/32919052359?pr=1359#step:8:239).

**Comment by ChrisSargent** [comment]
well..... `yarn dedupe` solved the `useScrollController` error but not another one that we get just from doing the openapi plugin upgrade so 🤷

**Comment by fpauer** [comment]
I just tried to go over the initial steps 
```
npx create-docusaurus@3.5.2 my-website --package-manager yarn
...
cd my-website
yarn start
```

And even the example demo does not work 👎 , I would say frustrating, I tried to force all docusaurus packages to be version 3.5.2 , also does not work.

```
Hook useScrollController is called outside the <ScrollControllerProvider>. 
ReactContextError
    at useScrollController (webpack-internal:///./node_modules/docusaurus-theme-openapi-docs/node_modules/@docusaurus/theme-common/lib/utils/scrollUtils.js:27:145)
    at useScrollPositionBlocker (webpack-internal:///./node_modules/docusaurus-theme-openapi-docs/node_modules/@docusaurus/theme-common/lib/utils/scrollUtils.js:45:63)
```

**Comment by IanVS** [comment]
I had problems upgrading from docusaurus 3.5 and plugin version 4.2 to 3.6 and 4.3 respectively.  A `pnpm dedupe` solved it.  It was still somehow using docusaurus 3.5 due to some transitive dependency chain that I didn't investigate too much.

**Comment by vtempest** [comment]
```
             Error: Can't render static file for pathname "/petstore31/user" 
       message: 'Hook useDocsSidebar is called outside the <DocsSidebarProvider>. '

```

similar issue with 4.3

**Comment by crypblizz8** [comment]
What worked for me (as `dedupe` did not work for me)

```
// package.json
    ...
    "docusaurus-plugin-openapi-docs": "4.2.0",
    "@docusaurus/core": "3.5.2",
    "@docusaurus/preset-classic": "3.5.2",
    "@docusaurus/theme-search-algolia": "3.5.2",
    ...
    
      "resolutions": {
    "@docusaurus/core": "3.5.2",
    "@docusaurus/theme-common": "3.5.2",
    "docusaurus-theme-openapi-docs": "4.2.0"
  }
```    

and 

```
rm -rf node_modules yarn.lock
yarn install
```

**Comment by zumma93** [comment]
I have upgrade docusaurus to 3.6.3 and upgrade docusaurus-plugin-openapi-docs to 4.3.0 
and convert petstore.yaml into mdx files and try docusaurus build, then i get following error: 

Error: Can't render static file for pathname "/API/create-users-with-array-input"
            at generateStaticFile (\node_modules\@docusaurus\core\lib\ssg\ssg.js:167:15)      
            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
            at async C:\Users\A13523\Workspace\Connect-developer-portal\node_modules\p-map\index.js:57:22 {
          [cause]: TypeError: Cannot read properties of null (reading 'store')
              at useSelector (server.bundle.js:332261:34)
              at MethodEndpoint (server.bundle.js:272560:784)
              at Uc (server.bundle.js:329991:44)
              at Xc (server.bundle.js:329993:253)
              at Z (server.bundle.js:329999:89)
              at Yc (server.bundle.js:330002:98)
              at $c (server.bundle.js:330001:140)
              at Z (server.bundle.js:329999:345)
              at Xc (server.bundle.js:329994:476)
              at Z (server.bundle.js:329999:89)
        },

**Comment by TaxNowAndrewY** [comment]
same running into this issue as well.  Was there any other resolution?
