### ISSUE TITLE
error in docusaurus 3.6.3 with faster

### ISSUE THREAD

**Issue by naviialto** [PaloAltoNetworks/docusaurus-openapi-docs#1028]
Using docusaurus-theme-openapi-docs@4.2.0 with rspack from faster in docusaurus 3.6.3 gives an error.

## install
```
cd project/
npx create-docusaurus@latest myweb classic --typescript
cd myweb/
yarn add @docusaurus/faster
yarn add docusaurus-theme-openapi-docs
yarn docusaurus start --host 0.0.0.0 --no-open
```

## settings
docusaurus.config.ts
```
  future: {
    experimental_faster: {
      swcJsLoader: true,
      swcJsMinimizer: true,
      swcHtmlMinimizer: true,
      lightningCssMinimizer: true,
      rspackBundler: true,
      mdxCrossCompilerCache: true,
    },
  },
 themes: ["docusaurus-theme-openapi-docs"],
 themeConfig: {
   // Replace with your project's social card
   image: 'img/docusaurus-social-card.jpg',
   navbar: {
     title: 'My Site',
     logo: {
```

## output
```
yarn run v1.22.22
$ docusaurus start --host 0.0.0.0 --no-open
[INFO] Starting the development server...
[SUCCESS] Docusaurus website is running at: http://localhost:3000/
●  ██████████████████████████████████████████████████ (9%) setup compilation
<e> [webpack-dev-middleware] [Error:   × TypeError: Cannot read properties of undefined (reading 'set')
<e>   │     at Object.fn (/home/wpg/project/myweb/node_modules/webpack/lib/ProvidePlugin.js:43:37)
<e>   │     at SyncHook.callAsyncStageRange (/home/wpg/project/myweb/node_modules/@rspack/lite-tapable/dist/index.js:240:21)
<e>   │     at SyncHook.callStageRange (/home/wpg/project/myweb/node_modules/@rspack/lite-tapable/dist/index.js:259:14)
<e>   │     at QueriedHook.call (/home/wpg/project/myweb/node_modules/@rspack/lite-tapable/dist/index.js:218:26)
<e>   │     at /home/wpg/project/myweb/node_modules/@rspack/core/dist/index.js:13673:28
<e>   │     at last.function (/home/wpg/project/myweb/node_modules/@rspack/core/dist/index.js:14471:25)
<e>   │
<e> ] {
<e>   code: 'GenericFailure'
<e> }
```

## env
```
node --version
v23.3.0
```

```
 "dependencies": {
   "@docusaurus/core": "3.6.3",
   "@docusaurus/faster": "^3.6.3",
   "@docusaurus/preset-classic": "3.6.3",
   "@mdx-js/react": "^3.0.0",
   "clsx": "^2.0.0",
   "docusaurus-theme-openapi-docs": "^4.2.0",
   "prism-react-renderer": "^2.3.0",
   "react": "^18.0.0",
   "react-dom": "^18.0.0"
 },
```

**Comment by omonk** [comment]
Your code block hides the error under a horizontal scroll

```
<e> [webpack-dev-middleware] [Error:   × TypeError: Cannot read properties of undefined (reading 'set')
```

We're seeing the same thing as well

**Comment by naviialto** [comment]
@omonk ok, fixed it

**Comment by erielmiquilino** [comment]
@omonk I was having the same problem, and this solution worked for me:
> ```
> yarn add docusaurus-theme-openapi-docs@0.0.0-953 docusaurus-plugin-openapi-docs@0.0.0-953
> ```

Everything is working perfectly now. Thanks for the guidance!

**Comment by sserrata** [comment]
Yeah, also a reminder to check/consult release notes as I'll try to include announcements of new features like these.
