### ISSUE TITLE
When using x-codeSamples you can't have two samples that use the same langauge

### ISSUE THREAD

**Issue by tjperry07** [PaloAltoNetworks/docusaurus-openapi-docs#1045]
## Describe the bug

If there are two samples that use the same language, it returns a Tab error. 

## Expected behavior

I should be able to have multiple code samples in the same language with different labels using x-codeSamples.

## Current behavior

Adding the example to my openapi file, causes an error. I tried the same file in other tools such as Redoc and Rapidoc, both display with no issues.

```json
        "x-codeSamples": [
          {
            "lang": "Python",
            "label": "KeyPair Auth",
            "source": "import requests\nimport json\n\nurl = \"https://app.<your-base-url>.coalescesoftware.io/scheduler/rerun\"\n\n# The private key needs to be escaped properly.\nkeypairkey = r\"\"\"-----BEGIN ENCRYPTED PRIVATE KEY-----\nXxx\nXxx\n-----END ENCRYPTED PRIVATE KEY-----\"\"\"\nkeypairpass = \"keypass\"\n\npayload = json.dumps({\n  \"runDetails\": {\n    \"runID\": \"<string>\"\n  },\n  \"userCredentials\": {\n    \"snowflakeUsername\": \"<string>\",\n    \"snowflakePassword\": \"<string>\",\n    \"snowflakeKeyPairKey\": keypairkey,\n    \"snowflakeKeyPairPass\": keypairpass,\n    \"snowflakeWarehouse\": \"<string>\",\n    \"snowflakeRole\": \"<string>\",\n    \"snowflakeAuthType\": \"Basic\"\n  },\n    \"parameters\": {\n      \"foo\": \"bar\"\n    }\n})\nheaders = {\n  'Content-Type': 'application/json',\n  'Accept': 'application/json',\n  'Authorization': 'Bearer bearerToken'\n}\n\nresponse = requests.request(\"POST\", url, headers=headers, data=payload)\n\nprint(response.text)\n\n"
          },
          {
            "lang": "Python",
            "label": "Basic Auth",
            "source": "import requests\nimport json\n\nurl = \"https://app.<your-base-url>.coalescesoftware.io/scheduler/startRun\"\n\npayload = json.dumps({\n  \"runDetails\": {\n    \"environmentID\": \"<string>\",\n    \"includeNodesSelector\": \"{ location: SAMPLE name: CUSTOMER } OR { location: SAMPLE name: LINEITEM }\",\n    \"excludeNodesSelector\": \"<string>\",\n    \"jobID\": \"<string>\"\n  },\n  \"userCredentials\": {\n    \"snowflakeUsername\": \"<string>\",\n    \"snowflakePassword\": \"<string>\",\n    \"snowflakeWarehouse\": \"<string>\",\n    \"snowflakeRole\": \"<string>\",\n    \"snowflakeAuthType\": \"Basic\"\n  },\n  \"parameters\": {\n    \"foo\": \"bar\"\n  }\n})\nheaders = {\n  'Content-Type': 'application/json',\n  'Accept': 'application/json',\n  'Authorization': 'Bearer bearerToken'\n}\n\nresponse = requests.request(\"POST\", url, headers=headers, data=payload)\n\nprint(response.text)\n"
          }
        ],
```

```
Docusaurus error: Duplicate values "Python" found in <Tabs>. Every value needs to be unique.
    at ensureNoDuplicateValue (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/tabsUtils.js:23:544)
    at eval (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/tabsUtils.js:23:867)
    at mountMemo (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:16407:19)
    at Object.useMemo (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:16852:16)
    at useMemo (webpack-internal:///./node_modules/react/cjs/react.development.js:1652:21)
    at useTabValues (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/tabsUtils.js:23:801)
    at useTabs (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/tabsUtils.js:26:165)
    at TabsComponent (webpack-internal:///./node_modules/docusaurus-theme-openapi-docs/lib/theme/ApiExplorer/CodeTabs/index.js:11:369)
    at renderWithHooks (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:15487:18)
    at mountIndeterminateComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20099:13)
```

## Possible solution

Don't check for unique language tab values.

## Steps to reproduce

Add this to your OpenAPI file, then generate again. Click on the endpoint to return the error. 

```json
        "x-codeSamples": [
          {
            "lang": "Python",
            "label": "KeyPair Auth",
            "source": "import requests\nimport json\n\nurl = \"https://app.<your-base-url>.coalescesoftware.io/scheduler/rerun\"\n\n# The private key needs to be escaped properly.\nkeypairkey = r\"\"\"-----BEGIN ENCRYPTED PRIVATE KEY-----\nXxx\nXxx\n-----END ENCRYPTED PRIVATE KEY-----\"\"\"\nkeypairpass = \"keypass\"\n\npayload = json.dumps({\n  \"runDetails\": {\n    \"runID\": \"<string>\"\n  },\n  \"userCredentials\": {\n    \"snowflakeUsername\": \"<string>\",\n    \"snowflakePassword\": \"<string>\",\n    \"snowflakeKeyPairKey\": keypairkey,\n    \"snowflakeKeyPairPass\": keypairpass,\n    \"snowflakeWarehouse\": \"<string>\",\n    \"snowflakeRole\": \"<string>\",\n    \"snowflakeAuthType\": \"Basic\"\n  },\n    \"parameters\": {\n      \"foo\": \"bar\"\n    }\n})\nheaders = {\n  'Content-Type': 'application/json',\n  'Accept': 'application/json',\n  'Authorization': 'Bearer bearerToken'\n}\n\nresponse = requests.request(\"POST\", url, headers=headers, data=payload)\n\nprint(response.text)\n\n"
          },
          {
            "lang": "Python",
            "label": "Basic Auth",
            "source": "import requests\nimport json\n\nurl = \"https://app.<your-base-url>.coalescesoftware.io/scheduler/startRun\"\n\npayload = json.dumps({\n  \"runDetails\": {\n    \"environmentID\": \"<string>\",\n    \"includeNodesSelector\": \"{ location: SAMPLE name: CUSTOMER } OR { location: SAMPLE name: LINEITEM }\",\n    \"excludeNodesSelector\": \"<string>\",\n    \"jobID\": \"<string>\"\n  },\n  \"userCredentials\": {\n    \"snowflakeUsername\": \"<string>\",\n    \"snowflakePassword\": \"<string>\",\n    \"snowflakeWarehouse\": \"<string>\",\n    \"snowflakeRole\": \"<string>\",\n    \"snowflakeAuthType\": \"Basic\"\n  },\n  \"parameters\": {\n    \"foo\": \"bar\"\n  }\n})\nheaders = {\n  'Content-Type': 'application/json',\n  'Accept': 'application/json',\n  'Authorization': 'Bearer bearerToken'\n}\n\nresponse = requests.request(\"POST\", url, headers=headers, data=payload)\n\nprint(response.text)\n"
          }
        ],
```
## Context

I need to display multiple code samples in the same language for special authentication cases.

## Your Environment

    "docusaurus-plugin-openapi-docs": "^4.0.1",
    "docusaurus-theme-openapi-docs": "^4.0.1",

**Comment by sserrata** [comment]
Hi @tjperry07, I appreciate the detailed issue and possible workaround, but I see this more as a feature request than a bug. 

That said, I think there's definitely room for improving how we handle `x-codeSamples`. I'd like to take more time to design a proper solution that works for everyone and would appreciate yours and others feedback along the way. In the meantime, I agree that swizzling is the appropriate work around for supporting this feature today.
