### ISSUE TITLE
Does not build on Cloudflare pages.

### ISSUE THREAD

**Issue by jonasfroeller** [PaloAltoNetworks/docusaurus-openapi-docs#1048]
## Current behavior

```
2024-12-14T23:22:54.502413Z	Cloning repository...
2024-12-14T23:22:55.203133Z	From https://github.com/xxx/xxx
2024-12-14T23:22:55.203563Z	 * branch            accb356ae07345fc81bf345ba922585ecfe57fa6 -> FETCH_HEAD
2024-12-14T23:22:55.203668Z	
2024-12-14T23:22:55.24815Z	HEAD is now at accb356 updates docusaurus and improves ux
2024-12-14T23:22:55.248619Z	
2024-12-14T23:22:55.324865Z	
2024-12-14T23:22:55.325312Z	Using v2 root directory strategy
2024-12-14T23:22:55.344778Z	Success: Finished cloning repository files
2024-12-14T23:22:56.727922Z	Checking for configuration in a Wrangler configuration file (BETA)
2024-12-14T23:22:56.728612Z	
2024-12-14T23:22:56.824559Z	No wrangler.toml file found. Continuing.
2024-12-14T23:22:56.977933Z	Detected the following tools from environment: npm@9.6.7, nodejs@18.17.1
2024-12-14T23:22:56.97841Z	Installing project dependencies: npm clean-install --progress=false
2024-12-14T23:23:05.853894Z	npm WARN deprecated mkdirp@0.3.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
2024-12-14T23:23:06.316791Z	npm WARN deprecated gauge@3.0.2: This package is no longer supported.
2024-12-14T23:23:18.08146Z	npm WARN deprecated @faker-js/faker@5.5.3: Please update to a newer version.
2024-12-14T23:23:22.312293Z	npm ERR! code 1
2024-12-14T23:23:22.318187Z	npm ERR! path /opt/buildhome/repo/node_modules/postman-code-generators
2024-12-14T23:23:22.324531Z	npm ERR! command failed
2024-12-14T23:23:22.329766Z	npm ERR! command sh -c node npm/deepinstall.js
2024-12-14T23:23:22.334694Z	npm ERR! Detected package manager: yarn
2024-12-14T23:23:22.33975Z	npm ERR! Detected yarn version: 3.6.3
2024-12-14T23:23:22.340027Z	npm ERR! Running pre-package script
2024-12-14T23:23:22.341741Z	npm ERR! Run successful languages.js saved in lib/assets
2024-12-14T23:23:22.34672Z	npm ERR! csharp-httpclient: touch yarn.lock && yarn workspaces focus --all --production
2024-12-14T23:23:22.351786Z	npm ERR! csharp-restsharp: touch yarn.lock && yarn workspaces focus --all --production
2024-12-14T23:23:22.35678Z	npm ERR! Failed to run yarn install on codegen csharp-httpclient, here is the error:
2024-12-14T23:23:22.361488Z	npm ERR! Failed to run yarn install on codegen csharp-restsharp, here is the error:
2024-12-14T23:23:22.366531Z	npm ERR! /opt/buildhome/repo/node_modules/postman-code-generators/node_modules/async/dist/async.js:324
2024-12-14T23:23:22.371435Z	npm ERR!             if (fn === null) throw new Error("Callback was already called.");
2024-12-14T23:23:22.376471Z	npm ERR!                                    ^
2024-12-14T23:23:22.380272Z	npm ERR! 
2024-12-14T23:23:22.385197Z	npm ERR! Error: Callback was already called.
2024-12-14T23:23:22.390636Z	npm ERR!     at /opt/buildhome/repo/node_modules/postman-code-generators/node_modules/async/dist/async.js:324:36
2024-12-14T23:23:22.395517Z	npm ERR!     at /opt/buildhome/repo/node_modules/postman-code-generators/node_modules/async/dist/async.js:3646:17
2024-12-14T23:23:22.400501Z	npm ERR!     at /opt/buildhome/repo/node_modules/postman-code-generators/npm/deepinstall.js:82:16
2024-12-14T23:23:22.40552Z	npm ERR!     at Array.forEach (<anonymous>)
2024-12-14T23:23:22.410123Z	npm ERR!     at /opt/buildhome/repo/node_modules/postman-code-generators/npm/deepinstall.js:71:14
2024-12-14T23:23:22.418789Z	npm ERR!     at /opt/buildhome/repo/node_modules/postman-code-generators/node_modules/async/dist/async.js:3641:28
2024-12-14T23:23:22.419465Z	npm ERR!     at replenish (/opt/buildhome/repo/node_modules/postman-code-generators/node_modules/async/dist/async.js:446:21)
2024-12-14T23:23:22.421185Z	npm ERR!     at iterateeCallback (/opt/buildhome/repo/node_modules/postman-code-generators/node_modules/async/dist/async.js:430:21)
2024-12-14T23:23:22.421614Z	npm ERR!     at /opt/buildhome/repo/node_modules/postman-code-generators/node_modules/async/dist/async.js:327:20
2024-12-14T23:23:22.422932Z	npm ERR!     at /opt/buildhome/repo/node_modules/postman-code-generators/node_modules/async/dist/async.js:3646:17
2024-12-14T23:23:22.423398Z	npm ERR! 
2024-12-14T23:23:22.423543Z	npm ERR! Node.js v18.17.1
2024-12-14T23:23:22.426152Z	
2024-12-14T23:23:22.431445Z	npm ERR! A complete log of this run can be found in: /opt/buildhome/.npm/_logs/2024-12-14T23_22_57_637Z-debug-0.log
2024-12-14T23:23:22.433774Z	Error: Exit with error code: 1
2024-12-14T23:23:22.438801Z	    at ChildProcess.<anonymous> (/snapshot/dist/run-build.js)
2024-12-14T23:23:22.443925Z	    at Object.onceWrapper (node:events:652:26)
2024-12-14T23:23:22.449575Z	    at ChildProcess.emit (node:events:537:28)
2024-12-14T23:23:22.454492Z	    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
2024-12-14T23:23:22.45968Z	Failed: build command exited with code: 1
2024-12-14T23:23:23.255711Z	Failed: error occurred while running build command
```

## Steps to reproduce

1. Deploy to cloudflare pages.

## Your Environment

- Version used: 4.3.0
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): npm@9.6.7, nodejs@18.17.1
- Operating System and version (desktop or mobile): probably linux
- Link to your project: /

**Comment by sserrata** [comment]
Hi @jonasfroeller, are you using `npm` or `yarn`? Your error output suggests it could be both, which could create a conflict with lock files and packages.

**Comment by jonasfroeller** [comment]
@sserrata I am using npm only. There is no yarn.lock present in the project.

**Comment by sebluy** [comment]
@jonasfroeller I just ran into the same issue and fixed it by adding an explicit package manager to `package.json`.
```  
"packageManager": "npm@10.8.2",
```
I'm guessing it's a npm version issue because I think by default Cloudflare was running on an older version.
