### ISSUE TITLE
[Bug] Docusaurus server-side rendering could not render static page with path ReactContextError

### ISSUE THREAD

**Issue by sradu** [PaloAltoNetworks/docusaurus-openapi-docs#172]
## Describe the bug

Running `npm run build` returns a lot of:

```
[ERROR] Docusaurus server-side rendering could not render static page with path /api/petstore/category/...
ReactContextError
```

## Expected behavior

It should build a static website.

## Current behavior

```
[ERROR] Unable to build website for locale en.
[ERROR] Error: Failed to compile with errors.
    at /Home/common/temp/node_modules/.pnpm/@docusaurus+core@2.0.0-rc.1_818345a8d7cf6af82aae687b15f8b782/node_modules/@docusaurus/core/lib/webpack/utils.js:180:24
    at /Home/common/temp/node_modules/.pnpm/webpack@5.74.0/node_modules/webpack/lib/MultiCompiler.js:554:14
    at processQueueWorker (/Home/common/temp/node_modules/.pnpm/webpack@5.74.0/node_modules/webpack/lib/MultiCompiler.js:491:6)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

## Your Environment

Docusaurus: 2.0.0-rc.1
OpenAPI-docs: 1.1.1

Using pnpm and rush.

Part of docusaurus.config:

```
    [
      'docusaurus-plugin-openapi-docs',
      {
        id: 'petstore',
        docsPluginId: 'apiPetstore',
        config: {
          petstore: { // Note: petstore key is treated as the <id> and can be used to specify an API doc instance when using CLI commands
            specPath: 'static/api/v1.yaml', // Path to designated spec file
            outputDir: 'docs/api/petstore', // Output directory for generated .mdx docs
            sidebarOptions: {
              groupPathsBy: 'tag',
              sidebarCollapsible: true,
              sidebarCollapsed: true,
            },
          },
        }
      },
    ],

    [
      '@docusaurus/plugin-content-docs',
      {
        path: 'docs/api/petstore',
        routeBasePath: '/api/petstore',
        id: 'apiPetstore',
        sidebarPath: require.resolve('./sidebars/petstore.js'),
        sidebarCollapsible: false,
        docLayoutComponent: '@theme/DocPage',
        docItemComponent: '@theme/ApiItem',
      },
    ],
```

plugins.js
```

const { ProvidePlugin } = require('webpack');
const path = require('path');

const tailwindPlugin = (context, options) => {
  return {
    name: 'tailwind-plugin',
    configurePostCss(postcssOptions) {
      postcssOptions.plugins = [
        require('postcss-import'),
        require('tailwindcss/nesting'),
        require('tailwindcss'),
        require('autoprefixer'),
      ];
      return postcssOptions;
    },
  };
};

const webpackPlugin = (context, options) => {
  return {
    name: 'webpack-plugin',
    configureWebpack(config) {
      return {
        module: {
          rules: [
            {
              test: /\.m?js/,
              resolve: {
                fullySpecified: false,
              },
            },
          ],
        },
        plugins: [
          new ProvidePlugin({
            process: require.resolve('process/browser'),
          }),
        ],
        resolve: {
          fallback: {
          },
          alias: {
          },
        },
      };
    },
  };
};


module.exports = { tailwindPlugin, webpackPlugin };
```

Is there any way to get more debug information than just ReactContextError?

**Comment by sradu** [comment]
This should be more helpful:

<img width="1589" alt="Screen Shot 2022-07-26 at 5 34 40 PM" src="https://user-images.githubusercontent.com/82214/181034710-62d9585d-c4e1-4c46-bb87-24131759e34a.png">

**Comment by sradu** [comment]
Apologies, this is a spurious bug report. It's a rush issue on my end.

**Comment by selankon** [comment]
I have a similar issue, how you fixed this finally?

**Comment by sradu** [comment]
All these ReactContextError bugs were my mistakes. Either dependency issues or bugs in swizzled jsx files.
