### ISSUE TITLE
[ERROR] TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by JnaneshD05** [PaloAltoNetworks/docusaurus-openapi-docs#454]
## Describe the bug
I am trying to generate the docs using commadn  yarn docusaurus gen-api-docs all .

I am getting error which is generic and unable to identify the issue in the yaml file. The same yaml file works for other presets like redoc. 

## Expected behavior

Successfully generate mdx files for all apis
## Current behavior

PS C:\Users\Administrator\Downloads\webdocs-master\webdocs-master> yarn docusaurus gen-api-docs all
yarn run v1.22.19
$ docusaurus gen-api-docs all
Successfully created "docs/api/cv/sidebar.js"
Successfully created "docs/api/cv/alert-operations.tag.mdx"
[ERROR] TypeError: Cannot read properties of undefined (reading 'type')
    at C:\Users\Administrator\Downloads\webdocs-master\webdocs-master\node_modules\docusaurus-plugin-openapi-docs\lib\markdown\createStatusCodes.js:69:48
    at Array.map (<anonymous>)
    at C:\Users\Administrator\Downloads\webdocs-master\webdocs-master\node_modules\docusaurus-plugin-openapi-docs\lib\markdown\createStatusCodes.js:68:45
    at guard (C:\Users\Administrator\Downloads\webdocs-master\webdocs-master\node_modules\docusaurus-plugin-openapi-docs\lib\markdown\utils.js:21:26)
    at createResponseHeaders (C:\Users\Administrator\Downloads\webdocs-master\webdocs-master\node_modules\docusaurus-plugin-openapi-docs\lib\markdown\createStatusCodes.js:65:30)
    at C:\Users\Administrator\Downloads\webdocs-master\webdocs-master\node_modules\docusaurus-plugin-openapi-docs\lib\markdown\createStatusCodes.js:286:41
    at Array.map (<anonymous>)
    at createStatusCodes (C:\Users\Administrator\Downloads\webdocs-master\webdocs-master\node_modules\docusaurus-plugin-openapi-docs\lib\markdown\createStatusCodes.js:264:33)
    at createApiPageMD (C:\Users\Administrator\Downloads\webdocs-master\webdocs-master\node_modules\docusaurus-plugin-openapi-docs\lib\markdown\index.js:44:51)
    at C:\Users\Administrator\Downloads\webdocs-master\webdocs-master\node_modules\docusaurus-plugin-openapi-docs\lib\index.js:195:54
## Steps to reproduce

1. create the docusaurus openapi app
2.replace the yaml file 
[Alert-operations.txt](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/files/10822181/Alert-operations.txt)

3.try yarn docusaurus gen-api-docs all
4.

## Your Environment

- Version used: Latest version
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): node.js 
- Operating System and version (desktop or mobile): Desktop
- Link to your project:

**Comment by ts-sdeb** [comment]
@JnaneshD05 Facing the same issue, what was the resolution?

**Comment by JnaneshD05** [comment]
Issue was with the yaml file . I can't remember exactly but it might be related to some incorrect schema
