### ISSUE TITLE
Generated sidebar.js doesn't load

### ISSUE THREAD

**Issue by xgp** [PaloAltoNetworks/docusaurus-openapi-docs#545]
## Describe the bug

`sidebar.js` generated file does not load on docusaurus start

## Expected behavior

The `sidebar.js` file that is generated should load and correctly render the sidebar. 

## Current behavior

```bash
$ yarn start
yarn run v1.22.19
$ docusaurus start --host 0.0.0.0
[INFO] Starting the development server...
[ERROR] Sidebars file at "/home/garth/projects/saascrud/phasetwo-docs/api/sidebar.js" failed to be loaded.
[ERROR] Loading of version failed for version current
[ERROR] Error: Invalid sidebar items collection `{"type":"doc","id":"phase-two-admin-rest-api"}` in sidebar 0: it must either be an array of sidebar items or a shorthand notation (which doesn't contain a `type` property). See https://docusaurus.io/docs/sidebar/items for all valid syntaxes.
    at normalizeSidebar (/home/garth/projects/saascrud/phasetwo-docs/node_modules/@docusaurus/plugin-content-docs/lib/sidebars/normalization.js:49:15)
    at /home/garth/projects/saascrud/phasetwo-docs/node_modules/@docusaurus/plugin-content-docs/lib/sidebars/normalization.js:57:66
    at /home/garth/projects/saascrud/phasetwo-docs/node_modules/lodash/lodash.js:13469:38
    at /home/garth/projects/saascrud/phasetwo-docs/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/home/garth/projects/saascrud/phasetwo-docs/node_modules/lodash/lodash.js:3032:24)
    at Function.mapValues (/home/garth/projects/saascrud/phasetwo-docs/node_modules/lodash/lodash.js:13468:7)
    at normalizeSidebars (/home/garth/projects/saascrud/phasetwo-docs/node_modules/@docusaurus/plugin-content-docs/lib/sidebars/normalization.js:57:29)
    at loadSidebars (/home/garth/projects/saascrud/phasetwo-docs/node_modules/@docusaurus/plugin-content-docs/lib/sidebars/index.js:81:74)
    at async doLoadVersion (/home/garth/projects/saascrud/phasetwo-docs/node_modules/@docusaurus/plugin-content-docs/lib/index.js:91:34)
    at async loadVersion (/home/garth/projects/saascrud/phasetwo-docs/node_modules/@docusaurus/plugin-content-docs/lib/index.js:113:28)
```
## Steps to reproduce

See code here: https://github.com/p2-inc/phasetwo-docs/tree/xgp/panetworks-openapi

1. Start with an existing docusaurus `2.3.1` repo
2. run `yarn add docusaurus-plugin-openapi-docs`
3. run `yarn add docusaurus-theme-openapi-docs`
4. update the `docusaurus.config.js` file with the `docusaurus-plugin-openapi-docs` and `@docusaurus/plugin-content-docs` plugins, configured like this: https://github.com/p2-inc/phasetwo-docs/blob/xgp/panetworks-openapi/docusaurus.config.js#L250
5. run `yarn docusaurus gen-api-docs all`
6. run `yarn start`
7. see error above

## Context

I'm unable to render the generated API documentation in docusaurus.

## Your Environment

- Version used: 1.7.0
- Environment name and version: Node.js v19.1.0. Yarn 1.22.19.
- Operating System and version (desktop or mobile): Ubuntu 20.04
- Link to your project: https://github.com/p2-inc/phasetwo-docs/tree/xgp/panetworks-openapi

**Comment by sserrata** [comment]
Hi @xgp, the versions you referenced are incompatible as documented on the doc site and README:

## Compatibility Matrix

| Docusaurus OpenAPI Docs | Docusaurus       |
| ----------------------- | ---------------- |
| 1.x.x                   | `>=2.0.1 <2.3.0` |
| 2.x.x (beta)            | `>=2.3.0`        |

**Comment by xgp** [comment]
Thanks @sserrata . I updated to docusaurus 2.2.0 and the plugin version 1.7.0. I am still encountering problems with my configuration. Now the generate task fails:
```bash
$ yarn docusaurus gen-api-docs all
yarn run v1.22.19
$ /home/garth/projects/saascrud/phasetwo-docs/node_modules/.bin/docusaurus gen-api-docs all

   ╭──────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                          │
   │                              Update available 2.2.0 → 2.4.0                              │
   │                                                                                          │
   │    To upgrade Docusaurus packages with the latest version, run the following command:    │
   │     `yarn upgrade @docusaurus/core@latest @docusaurus/plugin-google-analytics@latest     │
   │        @docusaurus/preset-classic@latest @docusaurus/theme-live-codeblock@latest`        │
   │                                                                                          │
   ╰──────────────────────────────────────────────────────────────────────────────────────────╯

/home/garth/projects/saascrud/phasetwo-docs/node_modules/@docusaurus/plugin-content-docs/lib/versions/files.js:123
        throw new Error(`The docs folder does not exist for version "${versionName}". A docs folder is expected to be found at ${path_1.default.relative(context.siteDir, contentPath)}.`);
              ^

Error: The docs folder does not exist for version "current". A docs folder is expected to be found at api.
    at getVersionMetadataPaths (/home/garth/projects/saascrud/phasetwo-docs/node_modules/@docusaurus/plugin-content-docs/lib/versions/files.js:123:15)
    at async createVersionMetadata (/home/garth/projects/saascrud/phasetwo-docs/node_modules/@docusaurus/plugin-content-docs/lib/versions/index.js:97:68)
    at async Promise.all (index 0)
    at async readVersionsMetadata (/home/garth/projects/saascrud/phasetwo-docs/node_modules/@docusaurus/plugin-content-docs/lib/versions/index.js:150:30)
    at async Object.pluginContentDocs [as plugin] (/home/garth/projects/saascrud/phasetwo-docs/node_modules/@docusaurus/plugin-content-docs/lib/index.js:32:30)
    at async initializePlugin (/home/garth/projects/saascrud/phasetwo-docs/node_modules/@docusaurus/core/lib/server/plugins/init.js:83:32)
    at async Promise.all (index 7)
    at async initPlugins (/home/garth/projects/saascrud/phasetwo-docs/node_modules/@docusaurus/core/lib/server/plugins/init.js:91:21)
    at async externalCommand (/home/garth/projects/saascrud/phasetwo-docs/node_modules/@docusaurus/core/lib/commands/external.js:17:21)
    at async file:///home/garth/projects/saascrud/phasetwo-docs/node_modules/@docusaurus/core/bin/docusaurus.mjs:213:3

Node.js v19.1.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Is this a flaw in my configuration? https://github.com/p2-inc/phasetwo-docs/blob/xgp/panetworks-openapi/docusaurus.config.js#L252 I have read through the docs and examples, and I'm unable to find the problem
```javascript 
  ...
  plugins: [
    [
      'docusaurus-plugin-openapi-docs',
      {
        id: "openapi",
        docsPluginId: "api",
        config: {
          phasetwo: { // Note: petstore key is treated as the <id> and can be used to specify an API doc instance when using CLI commands
            specPath: "openapi.yaml", // Path to designated spec file
            outputDir: "api", // Output directory for generated .mdx docs
            baseUrl: "/api",
            sidebarOptions: {
              groupPathsBy: "tag",
            },
          }
        }
      },
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        id: "api",
        path: "api",
        breadcrumbs: true,
        routeBasePath: "api",
        include: ["**/*.md", "**/*.mdx"],
        sidebarPath: "api/sidebar.js",
        docLayoutComponent: "@theme/DocPage",
        docItemComponent: "@theme/ApiItem", // add @theme/ApiItem here
      },
    ],
  ],
  themes: ["@docusaurus/theme-live-codeblock","docusaurus-theme-openapi-docs"],
  ...
```

**Comment by xgp** [comment]
Removing the `plugin-content-docs` and running generate works to create the `api` dir and generate the `.mdx` files, but then I'm back to the same spot when I add it back and try to run `yarn start`.

```bash
$ yarn start
yarn run v1.22.19
$ docusaurus start --host 0.0.0.0

   ╭──────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                          │
   │                              Update available 2.2.0 → 2.4.0                              │
   │                                                                                          │
   │    To upgrade Docusaurus packages with the latest version, run the following command:    │
   │     `yarn upgrade @docusaurus/core@latest @docusaurus/plugin-google-analytics@latest     │
   │        @docusaurus/preset-classic@latest @docusaurus/theme-live-codeblock@latest`        │
   │                                                                                          │
   ╰──────────────────────────────────────────────────────────────────────────────────────────╯

[INFO] Starting the development server...
[ERROR] Sidebars file at "/home/garth/projects/saascrud/phasetwo-docs/api/sidebar.js" failed to be loaded.
[ERROR] Loading of version failed for version current
[ERROR] Error: Invalid sidebar items collection `{"type":"doc","id":"i/phase-two-admin-rest-api"}` in sidebar 0: it must either be an array of sidebar items or a shorthand notation (which doesn't contain a `type` property). See https://docusaurus.io/docs/sidebar/items for all valid syntaxes.
    at normalizeSidebar (/home/garth/projects/saascrud/phasetwo-docs/node_modules/@docusaurus/plugin-content-docs/lib/sidebars/normalization.js:49:15)
    at /home/garth/projects/saascrud/phasetwo-docs/node_modules/@docusaurus/plugin-content-docs/lib/sidebars/normalization.js:57:66
    at /home/garth/projects/saascrud/phasetwo-docs/node_modules/lodash/lodash.js:13469:38
    at /home/garth/projects/saascrud/phasetwo-docs/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/home/garth/projects/saascrud/phasetwo-docs/node_modules/lodash/lodash.js:3032:24)
    at Function.mapValues (/home/garth/projects/saascrud/phasetwo-docs/node_modules/lodash/lodash.js:13468:7)
    at normalizeSidebars (/home/garth/projects/saascrud/phasetwo-docs/node_modules/@docusaurus/plugin-content-docs/lib/sidebars/normalization.js:57:29)
    at loadSidebars (/home/garth/projects/saascrud/phasetwo-docs/node_modules/@docusaurus/plugin-content-docs/lib/sidebars/index.js:81:74)
    at async doLoadVersion (/home/garth/projects/saascrud/phasetwo-docs/node_modules/@docusaurus/plugin-content-docs/lib/index.js:91:34)
    at async loadVersion (/home/garth/projects/saascrud/phasetwo-docs/node_modules/@docusaurus/plugin-content-docs/lib/index.js:113:28)
[INFO] Docusaurus version: 2.2.0
Node version: v19.1.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by xgp** [comment]
It does appear that the generated `sidebar.js` isn't valid against the docusaurus spec https://github.com/p2-inc/phasetwo-docs/blob/xgp/panetworks-openapi/api/sidebar.js

**Comment by xgp** [comment]
@sserrata Thanks for the help!
