### ISSUE TITLE
Error with Docusaurus 2.4.0

### ISSUE THREAD

**Issue by crazyfx1** [PaloAltoNetworks/docusaurus-openapi-docs#547]
## Describe the bug

Error `could not find react-redux context value; please ensure the component is wrapped in a <Provider>` with Docusaurus 2.4.0

## Expected behavior

Docs should render without error.

## Current behavior

When running the docs app, the generated doc pages show an error message:
```
could not find react-redux context value; please ensure the component is wrapped in a <Provider>
    at useReduxContext (webpack-internal:///./node_modules/react-redux/es/hooks/useReduxContext.js:30:11)
    at useSelector (webpack-internal:///./node_modules/react-redux/es/hooks/useSelector.js:135:28)
    at MethodEndpoint (webpack-internal:///./node_modules/docusaurus-theme-openapi-docs/lib-next/theme/ApiDemoPanel/MethodEndpoint/index.js:13:492)
    at renderWithHooks (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:14986:18)
    at mountIndeterminateComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:17812:13)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19050:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3946:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3995:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4057:31)
    at beginWork$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23960:7)
```

## Steps to reproduce

1. Install Docusaurus 2.4.0
2. Install 2.0.0-beta.2
3. Generate petstore.yaml sample
4. Start app and navigate to a generated doc file.

## Your Environment

npm list:
```
+-- @docusaurus/core@2.4.0
+-- @docusaurus/module-type-aliases@2.4.0
+-- @docusaurus/preset-classic@2.4.0
+-- @mdx-js/react@1.6.22
+-- @tsconfig/docusaurus@1.0.7
+-- clsx@1.2.1
+-- docusaurus-plugin-openapi-docs@2.0.0-beta.2
+-- docusaurus-theme-openapi-docs@2.0.0-beta.2
+-- prism-react-renderer@1.3.5
+-- react-dom@17.0.2
+-- react@17.0.2
`-- typescript@4.9.5
```

- Version used: 2.0.0-beta.2
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by crazyfx1** [comment]
I overlooked to set 

```
          docLayoutComponent: "@theme/DocPage",
          docItemComponent: "@theme/ApiItem" // Derived from docusaurus-theme-openapi-docs
```

**Comment by AhmedCoolProjects** [comment]
Didn't work for me actually  even I have the same versions
![image](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/72823374/546a5669-83b3-4d30-a917-72d4bb9a579d)

**Comment by AhmedCoolProjects** [comment]
![image](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/72823374/76d9b6ee-77c3-41ba-8d80-4dce244f0d83)

**Comment by liudonghua123** [comment]
I am using docusaursu v3. and `docLayoutComponent` could not use or I will got the following error in the console.

![image](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/2276718/d8cad25b-c8f3-41f7-8b4c-8630b52af131)

And when I only add `docItemComponent: "@theme/ApiItem"`, another errors shown on the page.

![image](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/2276718/5c92cbde-9a25-4b18-9c20-636c83181051)

If I [change the `docLayoutComponent` to `docRootComponent`](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/654#issuecomment-1895970081) . Another errors shown.

![image](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/2276718/3fbe863b-43c4-4917-8970-aaca0f855101)

**Comment by leoncraggs** [comment]
instead of  `docLayoutComponent :"@theme/ApiItem"` I had to use `docRootComponent: "@theme/DocRoot"`
