### ISSUE TITLE
Hook useDoc is called outside the <DocProvider>.

### ISSUE THREAD

**Issue by tripheo0412** [PaloAltoNetworks/docusaurus-openapi-docs#580]
## Describe the bug
```
git clone https://github.com/PaloAltoNetworks/docusaurus-openapi-docs.git
git checkout v2.0.0
```
And using demo folder from the repo.
With `2.0.0-beta.3` Whenever render any page with API docs using `@theme/ApiItem` I got `Hook useDoc is called outside the <DocProvider>.`

## Expected behavior

Docusaurus render without issue.

## Current behavior

Got error when render API docs page

```
ERROR
Hook useDoc is called outside the <DocProvider>. 
ReactContextError
    at useDoc (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/doc.js:28:112)
    at DocItemMetadata (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/DocItem/Metadata/index.js:13:139)
    at renderWithHooks (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:14986:18)
    at mountIndeterminateComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:17812:13)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19050:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3946:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3995:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4057:31)
    at beginWork$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23960:7)
    at performUnitOfWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:22772:12)
```

## Steps to reproduce

1. `git clone https://github.com/PaloAltoNetworks/docusaurus-openapi-docs.git`
2. `git checkout v2.0.0`
3. Add to package.json
```
"resolutions": {
    "react-live": ">=3.1.1 <4.1.0"
  },
```
4. `yarn install`
5. `yarn start`
6. Got error

## Screenshots

<img width="1304" alt="image" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/25382052/b55aa730-5899-4959-b462-f876bb86454e">

## Your Environment

- Version used: Docusaurus `2.4.0`, plugin-openapi-docs and theme `2.0.0-beta.3`, yarn `1.22.19`
- Environment name and version: Node 18.16.0
- Operating System and version (desktop or mobile): Windows 11, MacOS 13

**Comment by tripheo0412** [comment]
@sserrata hi! We use the exact package.json in the demo folder on branch v2.0.0

**Comment by tripheo0412** [comment]
@sserrata we did delete node_modules and lock file in between try combinations of docusaurus version 2.3.1/2.4.0/2.4.1 with the plugins + theme version v2.0.0-beta.3

Docusaurus v2.2.0 works perfectly with plugins + theme v1.7.3

It just I'm excited with the beta and want to try it out :) Thank you for your  work 🙏

**Comment by Vardominator** [comment]
@sserrata Do you plan on supporting this for the latest version of Docusaurus anytime soon?

**Comment by xenobytezero** [comment]
I'm continuing to get this issue, and have rolled back everything progressively (all the way back to Docusaurus 2.2.0 / Plugin 1.4.4, which was said to work in [this comment](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/323#issuecomment-1314769304) ) with no success, I assume its something else going on in my config. was there any progress on getting to the root of this?

**Comment by justinrossack** [comment]
Any fix? I have the same issue.

**Comment by clarkmcc** [comment]
Same issue here. When I remove these lines from the config it goes away
```
docLayoutComponent: "@theme/DocPage",
docItemComponent: "@theme/ApiItem",
```

**Comment by johnrengelman** [comment]
I'm getting this same error with these versions:
@docusaurus/core: 3.1.1
docusaurus-plugin-openapi-docs: 3.0.0-beta.10
docusaurus-theme-openapi-docs: 3.0.0-beta.10

Error:
```
Hook useDoc is called outside the <DocProvider>. 
ReactContextError
    at useDoc (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/doc.js:30:112)
    at DocItemMetadata (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/DocItem/Metadata/index.js:15:139)
    at renderWithHooks (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:16306:18)
    at mountIndeterminateComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20070:13)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21583:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4165:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4214:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4278:31)
    at beginWork$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:27447:7)
    at performUnitOfWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26556:12)
```

One things, I'm doing is using this plugin with a 2nd installation of the `docs` plugin:

```
plugins: [
    require.resolve("docusaurus-lunr-search"),
    [
      "docusaurus-plugin-openapi-docs",
      {
        id: "apiDocs",
        docsPluginId: "apis",
        config: {...}
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        id: "apis",
        sidebarPath: require.resolve('./sidebars/apis.ts'),
        path: "gen/apis",
        routeBasePath: "/apis",
        editUrl: ({versionDocsDirPath, docPath}) =>
        `https://<made up repo>/edit/main/${versionDocsDirPath}/${docPath}`,
        docItemComponent: "@theme/ApiItem"
      } satisfies DocsPlugin.Options,
    ]
```

**Comment by sangaline** [comment]
I'm getting the same error with both docusaurus v3.0.1 and v3.1.1 against v3.0.0-beta.10, but I'm not using a second installation of the docs plugin. There was some discussion of this in #654 and the [recommendation](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/654#issuecomment-1895970081) was to set `docRootComponent: '@theme/DocRoot'` in the config. I get the error with or without this setting.

```typescript
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          docItemComponent: '@theme/ApiItem',
          docRootComponent: '@theme/DocRoot',
        },
```

I've tried many different version pairings between docusaurus and the plugin, and I get the same error each time.

@johnrengelman Do you still get the same error if you remove your second docs installation?

**Comment by sserrata** [comment]
FWIW, the `docRootComponent` option is not required for the plugin theme to work with v3. If you continue to encounter issues, I recommend starting from a fresh docusaurus site, using the latest release, to help avoid dependency conflicts. I did this a week ago and have successfully tested 3.1.1 and 3.2.0 with no issues. Every time I have encountered this issue there has, without fail, been a dependency conflict observable in my lock file. As I mentioned before, thoroughly scrub your lock file to sniff out any potential conflicts and pin dependencies if necessary/appropriate.

**Comment by sangaline** [comment]
Yes, there must have been a dependency conflict in my case. I had already been deleting `yarn.lock` and `node_modules` before trying different versions when I was getting the error. After removing all of the dependencies from `package.json` and incrementally adding them back from most core to least core (*i.e.* starting with docusaurus core packages, then the openapi plugin, and finally other third party plugins), I was able to get things working. I'm not sure exactly which dependency conflict was causing the issue, but v3.0.0-beta.10 is now working with v3.2.0 after following that approach.

**Comment by ChrisSargent** [comment]
running a `yarn dedupe` solved this for us.

**Comment by trajan0x** [comment]
I'm seeing a similiar issue to @sangaline (and also with or without docRoot.

My repo is open source so this is pretty easy to replicate:

1. `git clone https://github.com/synapsecns/sanguine`
2. `git checkout 066baa6627026dd3a56cc23fcedef4edbe5e82aa` (this commit: https://github.com/synapsecns/sanguine/pull/2603/commits/066baa6627026dd3a56cc23fcedef4edbe5e82aa(
3. `nvm use`
4. `yarn` (this is a yarn workspaces monorepo so this gets run from root of the repo)
5. `cd packages/docs/bridge`
6. `yarn build`

Error output looks like this:

<img width="1504" alt="image" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/83933037/e625ec77-c7fb-42cd-9fd8-c6b446f1b45a">

```Error: Docusaurus server-side rendering could not render static page with path /docs/Services/Signer because of error: Hook useDoc is called outside the <DocProvider>. 
    at serverEntry_render (main:56441:358)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:447:9)
    at async /Users/trajan0x/sanguine/node_modules/p-map/index.js:57:22 {
  [cause]: ReactContextError
      at useDoc (main:56695:112)
      at DocItemMetadata (main:14235:148)
      at Uc (main:59953:44)
      at Xc (main:59955:253)
      at Z (main:59961:89)
      at Yc (main:59964:98)
      at $c (main:59963:140)
      at Z (main:59961:345)
      at Yc (main:59964:98)
      at $c (main:59963:140) {
    message: 'Hook useDoc is called outside the <DocProvider>. '
  }
}
```

**Comment by sserrata** [comment]
As stated before, this error is associated with mismatches between docusaurus deps and the plugin.
