### ISSUE TITLE
TypeError error on Generation of docs

### ISSUE THREAD

**Issue by cryptodam** [PaloAltoNetworks/docusaurus-openapi-docs#592]
## Describe the bug
When I generate the doc I have the following error:
TypeError: Cannot create property 'description' on boolean 'true'

## Expected behavior

generation of the doc

## Current behavior

Error stated above. Then the generation stopped. The yaml file works well on many other openAPi tools (swagger etc..)

## Steps to reproduce

I can provide a sample unfortunatelly. Have you ever come accross this error. Thanks

## Screenshots
[ERROR] TypeError: Cannot create property 'description' on boolean 'true'
    at createItems (/Users/damienribault/git/ext-api-spec/node_modules/docusaurus-plugin-openapi-docs/lib/openapi/openapi.js:109:45)
    at processOpenapiFile (/Users/damienribault/git/ext-api-spec/node_modules/docusaurus-plugin-openapi-docs/lib/openapi/openapi.js:441:19)
    at async /Users/damienribault/git/ext-api-spec/node_modules/docusaurus-plugin-openapi-docs/lib/openapi/openapi.js:408:35
    at async Promise.all (index 0)
    at async processOpenapiFiles (/Users/damienribault/git/ext-api-spec/node_modules/docusaurus-plugin-openapi-docs/lib/openapi/openapi.js:418:22)
    at async generateApiDocs (/Users/damienribault/git/ext-api-spec/node_modules/docusaurus-plugin-openapi-docs/lib/index.js:93:39)
    at async Command.<anonymous> (/Users/damienribault/git/ext-api-spec/node_modules/docusaurus-plugin-openapi-docs/lib/index.js:378:21)

## Your Environment

- Version used: 2.0.0beta3
- nodejs 18.14.2
- macos m1

**Comment by sserrata** [comment]
unable to reproduce
