### ISSUE TITLE
Fronmatter api parameter too long

### ISSUE THREAD

**Issue by wkotlowski** [PaloAltoNetworks/docusaurus-openapi-docs#793]
## Describe the bug

The generated `api` frontmatter parameter may be too long causing the page to crash

## Expected behavior

The frontmatter's `api` parameter has a fixed length.

## Current behavior

I generated some API previews for the company I have a contract with as a TW and visiting the page only for one endpoint causes the docusaurus page to crash with the following error:

```
Cannot read properties of undefined (reading 'push') TypeError: Cannot read properties of undefined (reading 'push')     at eval (webpack-internal:///./node_modules/docusaurus-theme-openapi-docs/lib/theme/ApiItem/index.js:13:470)     at Array.forEach (<anonymous>)     at ApiItem (webpack-internal:///./node_modules/docusaurus-theme-openapi-docs/lib/theme/ApiItem/index.js:13:381)     at renderWithHooks (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:16306:18)     at updateFunctionComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19584:20)     at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21597:16)     at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4165:14)     at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4214:16)     at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4278:31)     at beginWork$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:27447:7)
```

I compared the mdx files for the broken page and working pages and noticed that my vscode does not render the api frontmatter parameter the same way - for the broken page it is of different colour with a highlight that tokenization is skipped for perfomance reasons. 

So being a smartass, I had a wild guess that maybe the api parameter is simply too long as it has 115k characters (no, I did not count it myself :P)  compared to other files with 8-10k characters. I took the value of a working api param, pasted it in the broken file and it works. I have no idea what the api parameter is responsible for and why does it work now.

## Steps to reproduce

I guess you could use my yaml file to build the preview. I added it here https://jumpshare.com/s/fMbq0iamCCu2JOhxlWrG 
I wanted to paste the api param value here but it's also too long for github comment to be processed :D 

## Context

I'm trying to add Financial Data Exchange APIs supported by the company I work for. Unfortunately, one of the APIs is broken for me. I am no dev but a tech writer responsible for creating the dev portal from scratch. So far, I managed, but this is the biggest issue I encountered while working on this project. Being no dev, I was not able to find the root cause, only a workaround.

## Your Environment

- Version used: 

```
  "dependencies": {
    "@docusaurus/core": ">=2.4.1 <=2.4.3",
    "@docusaurus/preset-classic": ">=2.4.1 <=2.4.3",
    "@docusaurus/theme-mermaid": "^2.4.3",
    "@mdx-js/react": "^1.6.22",
    "clsx": "^1.1.1",
    "docusaurus-plugin-openapi-docs": "2.1.3",
    "docusaurus-theme-openapi-docs": "2.1.3",
    "prism-react-renderer": "^1.3.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
```
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): node v21.5.0, chrome 122.0.6261.128 (Official Build) (x86_64)
- Operating System and version (desktop or mobile): macOs
- Link to your project:

**Comment by wkotlowski** [comment]
Hi @sserrata, sorry for the lack of a prompt reply -- I was sick for a couple of days and could not stand sitting by the monitor :).

I tried loading the spec using swagger editor and redoc online demo (https://redocly.github.io/redoc/) and had no issues.

**Comment by sserrata** [comment]
Hi @wkotlowski, no worries at all. 

Maybe I took to long to download/access the file?

![Screenshot 2024-06-28 at 11 02 56 AM](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/9343811/2ea8b91a-ff26-4512-845a-f6868e613070)

**Comment by ClementGre** [comment]
I reproduced this issue with a simple auth_status.api.mdx file containing only the header:

```mdx
---
id: auth-status
title: "auth_status"
description: "auth_status"
sidebar_label: "auth_status"
hide_title: true
hide_table_of_contents: true
api: eJxtUsFu2zAM/ZWB57TxultuGTAMveywLcCAoAgYmYnV2pJK0UEDw/8+UjZcZN3J1iP1+N4TBxA8Z9jsYdtLQ0G8Q/ExwNMKYiIuh8caNoBaP2RB6TOsICFjR0JsdwcIetCeP3e7THyn/SvwQQH9ZtdQh7AZQK7JmnwQOhNr6RS5Q1GoV+zLgyKdD77rO9hU46gKmHKKIVO26w9VZZ+asmOfisgywEUlDGI1TKmdDayfszUMH+fH4zM5AWN/7T1Tbe61xbeKFSMqevKpEhJbDOInDZPPhSoL+3CGcTXf/19lpvpQ0jvBnO5hF9TCyXNHltsPC8WkfMUQCrKtNRbTIl5aY7CQf0204/gOT9DPOTMtjVa9zev2FfUFm2iPeyYpjyqNHtbWtF6afDjFIn8eg+yaa/JvB037cET3oj0XXYRpQHX/+b4y3ylm6TC8p1Zmf1pob3Qt4Qi9yTq1qIaVo+eS6aRrXwhuHqfRGVYYhiNm2nE7jga/9sRXxfX3guzxaLr3T0rYENa6erayL6QtsHWOknm/YNsXkf+ukO3hktP3b781179F0RZJ
sidebar_class_name: "get api-method"
info_path: docs/endpoints/archypix-app-back
custom_edit_url: null
---
```

If I change the api value to be shorter, the error is fixed. I guess ``docusaurus gen-api-docs all`` just puts a value too large on the api field.

**Comment by ClementGre** [comment]
Here is my openapi.json file:
[openapi.json](https://github.com/user-attachments/files/16978816/openapi.json)

**Comment by mrminht2000** [comment]
I have the same issue after generate documents from my [openapi.json](https://github.com/user-attachments/files/17930867/openapi.json) file.
Some of documents are broken with above error, anything else works fine and I still dont know what are differences.

`---
id: get-customer-listcustomers-get
title: "API truy xuất danh sách khách hàng"
description: "API truy xuất danh sách khách hàng"
sidebar_label: "API truy xuất danh sách khách hàng"
hide_title: true
hide_table_of_contents: true
api: eJzNVlFvG0UQ/iurfSriQkKQQD2pD0mhwWppShN4SS203pt4t77bvezNWTHWPfPAA4oQQjxUIlhRBUIqUXm6E+qDK/7H/ROYO59jO05qWpDwg+98tzPzzTffjGfIUXQT7h/w22mCNgK3FWve9ngAiXQ6Rm0N9/nWgxZDlw7YcVrmZ8gCYRRLxqdSsZ6qLmr8o+lyj9sYnCCrVsB9vgPY+L2nE5ST++SLHUDu8Vg4EQGCIwRDbkQE3OfSBsA9rinwpym4AV+Esz/+NWI9XeYvorn4DBVYFo1Hi6gcHKXaQcD9QxEm4PFEKogE94ccBzEFTdBp0+VZ5k1xVJc3wIHjX8y/AkRag0Li/TTqgHsTRElZnLCXJ7osvjIMlS3zU/26oDpOGKlaQXI9oFbApNLMqPGpUctiwXEcUsF9dOmy0NqQUjRClMw/hW5FxqF1kcD60Xub3OMmDUPRCWESIZsFrY0M0wAeQmT78Erst8fPWVjmZwOGavw7kajNrPRbAeuUxdfs2I5PWVAW54Kho6KHIsFPbKAPNQR3nI1W4rhjbciXgN23KMLXAFrZtUzfagle/euB1QYn9w+hDyaFOWh1CY7XFihcBeyOs2ncCl4pBqPGzxek+TYReYtt+JMcgrJ4xkISaTpppGrmyDIfMTk+lUt8rERwraQFvczmcO9y2a5rNVUWTzTrakG9JAbs5UlZfKfn4Idl/tQwmZbFiWY3jCrz84ipsvieoSuLUWXyremSjH6YM5yoibLf1xHsoYjit1bK8kOBQCazqQYCYQ3p4Wy6ez0dX5/iHs2L8M/fymJUgcxHhnWVJrjfsKNULAO0inr26nFybTH2Re8V0/cqdLIivdLSfwlw1wXgtgcNxqMrMObPYnZc5i9ij4CdpTQicumzR7WDzuDWWg8Gjzi70YMBi9X4J8M6JAJkypIEKMEnpuuxoDJfY0mZ/0FfjeNJk6iy+JlhWZz/LckyH0V0/qlZTTRL5vuWlBBjk50CEVTjdmEvqA6xj5u3i6PkqkAeB5NGtHaIOA61rDaG9ceJNbydZW1ylMTWJFDN/M2NDbosMJtKCQlNcPp7BIN05JI3fziDIXa0naCuvGaLuex2HoOkhCdQbf07ow+djR1IgbMsgkydxkG1u2yDcOC4f9Am+BGgsrQAdSd7Diru8/X+5vp0BeLkwPWb3Sd1IdGMGCf++npopQiVTdD/YOPm+5xcNtH2KJ2alybmlF0R67tAImxqmKKyTn9ZEbJQSkpKm0NbmWukbuB3tcXPNeCd+9tsNwbDaBn0OIGsOXr3nQ2eeTy2CUaiYreJtPKCOEf68KJ4/8DFJFuEY1yPQ6ENYaoIHE6oPuB9WgUuyG57nOikN8NhRyTwmQuzjB7XfUslCHRCU+GiwFdC/V909VIWejCYG019EaZ0qpJQXzhdz72DduY1QqDUa7NpyzdWl9ppTts7H+1zj4uUCJ+VYK+S4OSGvDevzCyiRW3WEOibhtBSk+GwFniWTc/Xr660mI6t+jRx1M6y7C95QdL5
sidebar_class_name: "get api-method"
info_path: apis/openapi/kiotvietfnb-open-api
custom_edit_url: null
---`
After deleted the value in **api** field, it worked but lost some extensions
Is there any solution or workaround for this error ?

**Comment by mrminht2000** [comment]
So, I decided to debug a little while, and found out where this error was thrown:
`docusaurus-theme-openapi-docs/lib/theme/ApiItem/index.js`

```
const paramsObject = {
    path: [],
    query: [],
    header: [],
    cookie: [],
  };
  item.parameters?.forEach((param) => {
    const paramType = param.in;
    const paramsArray = paramsObject[paramType];
    paramsArray.push(param);
  });
```
In my case, after generated docs, Api item's parameters look like this:
```
0: {name: 'code', in: 'Query', description: 'Tìm kiếm khách hàng theo mã khách hàng', required: false, schema: {…}}
1: {name: 'name', in: 'Query', description: 'Tìm kiếm khách hàng theo tên khách hàng', required: false, schema: {…}}
2: {name: 'contactNumber', in: 'Query', description: 'Tìm kiếm khách hàng theo số điện thoại', required: false, schema: {…}}
3: {name: 'branchIds', in: 'Query', description: 'Id chi nhánh', required: false, explode: true, …}
4: {name: 'includeRemoveIds', in: 'Query', description: 'Có lấy thông tin danh sách Id bị xoá dựa trên lastModifiedFrom', required: false, schema: {…}}
```
As you can see, the problem happened because the parameterTypes, or param **in** were uppercase, so **paramsArray = paramsObject[paramType]** would return _undentified_.

In @ClementGre 's situation,  the api item's parameters contain empty values for param **in**, which caused the same error as mine.
```
0: {name: 'User-Agent', in: '', schema: {…}}
1: {name: 'X-User-Id', in: '', schema: {…}}
```

**Comment by sserrata** [comment]
Hi @mrminht2000, thanks for troubleshooting. Yes, it makes sense since the plugin strictly requires a value for `in` and that it be lowercase. Were you able to get it to work by correcting those issue(s)?

**Comment by sserrata** [comment]
Hi @wkotlowski, following up on the original issue:

> So being a smartass, I had a wild guess that maybe the api parameter is simply too long as it has 115k characters (no, I did not count it myself :P) compared to other files with 8-10k characters. I took the value of a working api param, pasted it in the broken file and it works. I have no idea what the api parameter is responsible for and why does it work now.

Do you think it's possible your issue actually stems from what @mrminht2000 pointed out, i.e. missing or non-lowercase `in` value(s)?

**Comment by ruida-shen** [comment]
Hi there, I am also having issues with the api parameter being too long, which results the mdx loader takes forever to load a single mdx file. Is there anyway to customize the api parameter in frontmatter, or any other solutions you could provide? Thanks a lot!

**Comment by sserrata** [comment]
Closing as this predates v3. Please upgrade to the latest Docusaurus and `docusaurus-plugin-openapi-docs`, retest, and open a new issue with a fresh repro if it still occurs. Thanks!
