### ISSUE TITLE
Language Tabs interment crash

### ISSUE THREAD

**Issue by rhumbertgz** [PaloAltoNetworks/docusaurus-openapi-docs#826]
## Describe the bug

I'm facing a runtime issue when switching from languages tabs. For some languages ( e.g., `curl` and `powershell`) it works perfectly, but if I add other languages (e.g., python, go, javascript)  it crashes.. I'm using the following four languages:

```
 languageTabs: [
      {
        highlight: "bash",
        language: "curl",
        logoClass: "bash",
      },
      {
        highlight: "powershell",
        language: "powershell",
        logoClass: "powershell",
      },
      {
        highlight: "javascript",
        language: "nodejs",
        logoClass: "nodejs",
        variant: "axios",
      },
      {
        highlight: "python",
        language: "python",
        logoClass: "python",
        variant: "requests",
      },
    ],
```

## Expected behavior

I added  v3.0.0-beta.10 to new project generated with the Docusaurus CLI. I'm using as reference the demo the demo 3.0.0-beta.10 which works fine running on a Codespace. I have checked all my dependencies and are identical to the one on the Demo. I don't see what I'm missing.

## Current behavior
I get this error whenever I add any other language than `curl` and `powershell`.

```
Uncaught runtime errors:
×
ERROR
Docusaurus error: The <Tabs> has a defaultValue "requests" but none of its children has the corresponding value. Available values are: restmethod. If you intend to show no default tab, use defaultValue={null} instead.
    at getInitialStateValue (webpack-internal:///./node_modules/.pnpm/@docusaurus+theme-common@3.3.2_@docusaurus+types@3.3.2_react-dom@18.3.1_react@18.3.1_typescript@5.2.2/node_modules/@docusaurus/theme-common/lib/utils/tabsUtils.js:24:57)
    at eval (webpack-internal:///./node_modules/.pnpm/@docusaurus+theme-common@3.3.2_@docusaurus+types@3.3.2_react-dom@18.3.1_react@18.3.1_typescript@5.2.2/node_modules/@docusaurus/theme-common/lib/utils/tabsUtils.js:26:275)
    at mountState (webpack-internal:///./node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom.development.js:16168:20)
    at Object.useState (webpack-internal:///./node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom.development.js:16881:16)
    at useState (webpack-internal:///./node_modules/.pnpm/react@18.3.1/node_modules/react/cjs/react.development.js:1624:21)
    at useTabs (webpack-internal:///./node_modules/.pnpm/@docusaurus+theme-common@3.3.2_@docusaurus+types@3.3.2_react-dom@18.3.1_react@18.3.1_typescript@5.2.2/node_modules/@docusaurus/theme-common/lib/utils/tabsUtils.js:26:270)
    at TabsComponent (webpack-internal:///./node_modules/.pnpm/docusaurus-theme-openapi-docs@3.0.0-beta.10_@docusaurus+core@3.3.2_@docusaurus+types@3.3.2_@t_4supdxkys5nyzwzue2bqmjp7my/node_modules/docusaurus-theme-openapi-docs/lib/theme/ApiExplorer/CodeTabs/index.js:8:369)
    at renderWithHooks (webpack-internal:///./node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom.development.js:15487:18)
    at mountIndeterminateComponent (webpack-internal:///./node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom.development.js:20099:13)
    at beginWork (webpack-internal:///./node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom.development.js:21622:16)
ERROR
Docusaurus error: The <Tabs> has a defaultValue "requests" but none of its children has the corresponding value. Available values are: restmethod. If you intend to show no default tab, use defaultValue={null} instead.
    at getInitialStateValue (webpack-internal:///./node_modules/.pnpm/@docusaurus+theme-common@3.3.2_@docusaurus+types@3.3.2_react-dom@18.3.1_react@18.3.1_typescript@5.2.2/node_modules/@docusaurus/theme-common/lib/utils/tabsUtils.js:24:57)
    at eval (webpack-internal:///./node_modules/.pnpm/@docusaurus+theme-common@3.3.2_@docusaurus+types@3.3.2_react-dom@18.3.1_react@18.3.1_typescript@5.2.2/node_modules/@docusaurus/theme-common/lib/utils/tabsUtils.js:26:275)
    at mountState (webpack-internal:///./node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom.development.js:16168:20)
    at Object.useState (webpack-internal:///./node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom.development.js:16881:16)
    at useState (webpack-internal:///./node_modules/.pnpm/react@18.3.1/node_modules/react/cjs/react.development.js:1624:21)
    at useTabs (webpack-internal:///./node_modules/.pnpm/@docusaurus+theme-common@3.3.2_@docusaurus+types@3.3.2_react-dom@18.3.1_react@18.3.1_typescript@5.2.2/node_modules/@docusaurus/theme-common/lib/utils/tabsUtils.js:26:270)
    at TabsComponent (webpack-internal:///./node_modules/.pnpm/docusaurus-theme-openapi-docs@3.0.0-beta.10_@docusaurus+core@3.3.2_@docusaurus+types@3.3.2_@t_4supdxkys5nyzwzue2bqmjp7my/node_modules/docusaurus-theme-openapi-docs/lib/theme/ApiExplorer/CodeTabs/index.js:8:369)
    at renderWithHooks (webpack-internal:///./node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom.development.js:15487:18)
    at mountIndeterminateComponent (webpack-internal:///./node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom.development.js:20099:13)
    at beginWork (webpack-internal:///./node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom.development.js:21622:16)
ERROR
Docusaurus error: The <Tabs> has a defaultValue "requests" but none of its children has the corresponding value. Available values are: restmethod. If you intend to show no default tab, use defaultValue={null} instead.
    at getInitialStateValue (webpack-internal:///./node_modules/.pnpm/@docusaurus+theme-common@3.3.2_@docusaurus+types@3.3.2_react-dom@18.3.1_react@18.3.1_typescript@5.2.2/node_modules/@docusaurus/theme-common/lib/utils/tabsUtils.js:24:57)
    at eval (webpack-internal:///./node_modules/.pnpm/@docusaurus+theme-common@3.3.2_@docusaurus+types@3.3.2_react-dom@18.3.1_react@18.3.1_typescript@5.2.2/node_modules/@docusaurus/theme-common/lib/utils/tabsUtils.js:26:275)
    at mountState (webpack-internal:///./node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom.development.js:16168:20)
    at Object.useState (webpack-internal:///./node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom.development.js:16881:16)
    at useState (webpack-internal:///./node_modules/.pnpm/react@18.3.1/node_modules/react/cjs/react.development.js:1624:21)
    at useTabs (webpack-internal:///./node_modules/.pnpm/@docusaurus+theme-common@3.3.2_@docusaurus+types@3.3.2_react-dom@18.3.1_react@18.3.1_typescript@5.2.2/node_modules/@docusaurus/theme-common/lib/utils/tabsUtils.js:26:270)
    at TabsComponent (webpack-internal:///./node_modules/.pnpm/docusaurus-theme-openapi-docs@3.0.0-beta.10_@docusaurus+core@3.3.2_@docusaurus+types@3.3.2_@t_4supdxkys5nyzwzue2bqmjp7my/node_modules/docusaurus-theme-openapi-docs/lib/theme/ApiExplorer/CodeTabs/index.js:8:369)
    at renderWithHooks (webpack-internal:///./node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom.development.js:15487:18)
    at mountIndeterminateComponent (webpack-internal:///./node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom.development.js:20099:13)
    at beginWork (webpack-internal:///./node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom.development.js:21622:16)
```

## My Environment

- Version used: 3.0.0-beta.10
- Environment name and version: node.js v20.12.2, Safari 17.4.1 (19618.1.15.11.14), Edge Version 124.0.2478.105, Chrome Version 124.0.6367.209.
- Operating System and version (desktop or mobile): MacOS 14.4.1 (23E224) & Linux Dev Container
- Package Manager: NPM & PNPM

**Comment by rhumbertgz** [comment]
I did some extra tests and I found out that only enabling "curl" and "powershell" everything works fine. if add any other language e.g., python, javascript, go it breaks.

**Comment by rhumbertgz** [comment]
I found out that for some reason the order matters. For my languages, any order than `bash`, `python`, `javascript`, `powershell` breaks. So keeping the order in which the languages are shown in the demo works 🪄

**Comment by sserrata** [comment]
Hi @rhumbertgz, yup, that's a known limitation. The goal would be to support any combination of languages in any order (ideally on a per API basis) which is on our roadmap.
