### ISSUE TITLE
Support for anyOf/minProperties for required schema properties.

### ISSUE THREAD

**Issue by tyler-mairose-sp** [PaloAltoNetworks/docusaurus-openapi-docs#976]
## Describe the bug

Given the following schema the generated page does not properly render and instead gives an error: 
```error
Docusaurus error: the <Tabs> component requires at least one <TabItem> children component
```

```yaml
post:
  tags:
  - Suggested Entitlement Description
  operationId: submitSedBatchRequest
  summary: Submit Sed Batch Request
  description: 'Submit Sed Batch Request.

    Request body has one of the following:
      - a list of entitlement Ids
      - a list of SED Ids
    that user wants to have description generated by LLM. 
    API responses with batchId that groups Ids together'
  requestBody:
    description: Sed Batch Request
    content:
      application/json:
        schema:
          description: Sed Batch Request
          type: object
          anyOf:
            - required: [entitlements]
            - required: [seds]
          properties:
            entitlements:
              description: list of entitlement ids
              type: array
              items:
                type: string
                example: 016629d1-1d25-463f-97f3-c6686846650
            seds:
              description: list of sed ids
              type: array
              items:
                type: string
                example: 016629d1-1d25-463f-97f3-c6686846650
```

## Expected behavior

Request body should display and show that you must specific either an array of entitlements or an array of sed ids.

## Current behavior

I receive the error above, I believe this is because the plugin is not accounting for this use-case in open api specification.

## Steps to reproduce

Create a schema with the use of anyOf property to denote that you must include either property.

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): Node v20.9.0
- Operating System and version (desktop or mobile): MacOS Sonoma 14.7
- Link to your project:

**Comment by ahelmy** [comment]
Hi @tyler-mairose-sp,
I tested the shared schema and the error is not reproducible, would you check if it is fixed?
Thanks

**Comment by wborn** [comment]
I'm running into the same error after upgrading Docusaurus to 3.7.0 and the OpenAPI Docs plug-in to 4.3.4. 

See this [upgrades branch](https://github.com/openremote/documentation/tree/upgrades).

To regenerate the API docs I run:

```
yarn clean-api-docs all
yarn gen-api-docs all
```

Then when I run `yarn build` it errors:

```
        Error: Can't render static file for pathname "/docs/next/rest-api/schemas/abstractnotificationmessage"
            at generateStaticFile (/home/wouter/git/openremote/documentation/node_modules/@docusaurus/core/lib/ssg/ssg.js:167:15)
            at async /home/wouter/git/openremote/documentation/node_modules/p-map/index.js:57:22 {
          [cause]: Error: Docusaurus error: the <Tabs> component requires at least one <TabItem> children component
              at getInitialStateValue (server.bundle.js:159591:1060)
              at server.bundle.js:159594:246
              at useReducer (server.bundle.js:169430:11)
              at Object.useState (server.bundle.js:169589:12)
              at exports.useState (server.bundle.js:46975:33)
              at useTabs (server.bundle.js:159594:241)
              at TabsComponent (server.bundle.js:992001:342)
              at renderWithHooks (server.bundle.js:170218:18)
              at renderElement (server.bundle.js:170356:14)
              at retryNode (server.bundle.js:170900:16)
        },
        Error: Can't render static file for pathname "/docs/next/rest-api/schemas/agentdescriptor"
            at generateStaticFile (/home/wouter/git/openremote/documentation/node_modules/@docusaurus/core/lib/ssg/ssg.js:167:15)
            at async /home/wouter/git/openremote/documentation/node_modules/p-map/index.js:57:22 {
          [cause]: Error: Docusaurus error: the <Tabs> component requires at least one <TabItem> children component
              at getInitialStateValue (server.bundle.js:159591:1060)
              at server.bundle.js:159594:246
              at useReducer (server.bundle.js:169430:11)
              at Object.useState (server.bundle.js:169589:12)
              at exports.useState (server.bundle.js:46975:33)
              at useTabs (server.bundle.js:159594:241)
              at TabsComponent (server.bundle.js:992001:342)
              at renderWithHooks (server.bundle.js:170218:18)
              at renderElement (server.bundle.js:170356:14)
              at retryNode (server.bundle.js:170900:16)
...
```

If I use `showSchemas: false` in `docusaurus.config.ts` it does seem to work.

**Comment by wborn** [comment]
@tyler-mairose-sp my issue got fixed with the new 4.3.6 release.
Maybe it also fixes your issue?
